controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_profile_edit:
    path: /profile/edit
    controller: App\Controller\ProfileController::edit